name = "platoscave"
compatibility_date = "2024-01-01"

# Serve static assets from dist directory
[assets]
directory = "./dist"

[vars]
VITE_API_URL = "https://api.jackie-courtney.com"
VITE_CF_ACCESS_CLIENT_ID = "ada6e202c3616ebbafb41999856b696c.access"

