tunnel: platos-cave-api
credentials-file: /Users/jackiecourtney/.cloudflared/c905d714-cb21-4932-ae77-9de2f30dcc77.json

ingress:
  - hostname: api.jackie-courtney.com
    service: http://localhost:5001
  - hostname: browser.jackie-courtney.com
    service: http://localhost:7900
  - service: http_status:404